name: crappital

services:
  mongodb:
    image: mongo:8.0.5
    container_name: crappital-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: crappital
      MONGO_INITDB_DATABASE: crappital
    volumes:
      - mongodb_data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: crappital-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      DB_URL: mongodb://root:crappital@mongodb:27017/crappital?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongodb_data:

