name: crappital

services:
  # mongodb:
  #   build:
  #     context: ./db
  #     dockerfile: Dockerfile
  #   container_name: crappital-mongo
  #   restart: unless-stopped
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   container_name: crappital-server
  #   restart: unless-stopped
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     DB_URL: mongodb://root:crappital@mongodb:27017/crappital?authSource=admin
  #   depends_on:
  #     - mongodb

  # client:
  #   build:
  #     context: ./crappital-client
  #     dockerfile: Dockerfile
  #   container_name: crappital-client
  #   restart: unless-stopped
  #   ports:
  #     - "9021:80"
  #   depends_on:
  #     - server

  devcontainer:
    image: mcr.microsoft.com/devcontainers/universal:latest
    command: sleep infinity
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts-jdk21
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
      - ./.devcontainer/casc.yml:/var/jenkins_home/casc.yml
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yml

volumes:
  #mongodb_data:
  jenkins_data:
