# https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/README.md

jenkins:
  systemMessage: |+
    Jenkins configured automatically by Jenkins Configuration as Code plugin
  
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "admin"
        name: "Crappital Admin"
        password: "#jbcrypt:$2a$10$1MFR./L9PVgac3Pi3LOe4OJsv.sN5DrbdrGKsnB8UfBW6T1TOWhwO"
        properties:
        - mailer:
            emailAddress: "admin@crappital.valid"

appearance:
  themeManager:
    disableUserThemes: false
    theme: "chocolate"

tool:
  git:
    installations:
    - name: "Default"
      home: "git"
      properties:
      - installSource: {}
  
  nodejs:
    installations:
    - name: "NodeJS 22"
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "22.14.0"
              npmPackagesRefreshHours: 72

jobs:
  - script: >
      pipelineJob('crappital-pipeline') {
        description('ci/cd pipeline for crappital')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/abelbakk/crappital.git')
                  credentialsId(null) 
                }
                branches('*/ci-cd-demo')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }