FROM jenkins/jenkins:lts-alpine-jdk21

ARG DOCKER_GID_FROM_HOST

USER root

RUN apk add --no-cache docker-cli

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt