name: crappital

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    command: sleep infinity
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspaces/crappital:cached
    restart: "no"
    networks:
      - crappital-net

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile.jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
      - ./jenkins/casc.yml:/var/jenkins_home/casc.yml
      - ..:/workspaces/crappital:cached
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yml
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    networks:
      - crappital-net

  prometheus:
    image: prom/prometheus:v3.7.3
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - crappital-net

  grafana:
    image: grafana/grafana:12.2.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
    - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - crappital-net

networks:
  crappital-net:
    name: crappital-net

volumes:
  jenkins_data:
