name: crappital

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
      args:
        - DOCKER_GID_FROM_HOST=$${$(stat -c '%g' /var/run/docker.sock)}
    command: sleep infinity
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
    networks:
      - crappital-net

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile.jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
      - ./jenkins/casc.yml:/var/jenkins_home/casc.yml
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yml
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    networks:
      - crappital-net

networks:
  crappital-net:
    name: crappital-net

volumes:
  jenkins_data:
