pipeline {
    
    agent {
        docker {
            image 'crappital-devcontainer:latest'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out git repo...'
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                parallel (
                    server: {
                        echo 'Installing dependencies for server...'
                        dir('server') {
                            sh 'npm ci'
                        }
                    },
                    client: {
                        echo 'Installing dependencies for client...'
                        dir('crappital-client') {
                            sh 'npm ci'
                        }
                    }
                )
            }
        }

        stage('Build') {
            steps {
                parallel (
                    server: {
                        echo 'Building server...'
                        dir('server') {
                            sh 'npm run build'
                        }
                    },
                    client: {
                        echo 'Building client...'
                        dir('crappital-client') {
                            sh 'npm run build-ci'
                        }
                    }
                )
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                dir('server') {
                    sh 'npm run test'
                }
            }
        }

        stage('Build Docker images') {
            steps {
                parallel (
                    server: {
                        echo "Building server image..."
                        sh 'docker build -t crappital-server:latest -f .devcontainer/build/server/Dockerfile.deploy .'

                        echo "Loading server image into kind..."
                        sh 'kind load docker-image crappital-server:latest'
                    },
                    client: {
                        echo 'Building client image...'
                        sh 'docker build -t crappital-client:latest -f .devcontainer/build/client/Dockerfile.deploy .'
                        
                        echo 'Loading client image into kind...'
                        sh 'kind load docker-image crappital-client:latest'
                    },
                    db: {
                        echo 'Building database image...'
                        sh 'docker build -t crappital-mongo:latest db/'
                        
                        echo 'Loading database image into kind...'
                        sh 'kind load docker-image crappital-mongo:latest'
                    }
                )
            }
        }

    }
    
}