pipeline {
    
    agent {
        docker {
            image 'crappital-devcontainer:latest'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out git repo...'
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                parallel (
                    server: {
                        echo 'Installing dependencies for server...'
                        dir('server') {
                            sh 'npm ci'
                        }
                    },
                    client: {
                        echo 'Installing dependencies for client...'
                        dir('crappital-client') {
                            sh 'npm ci'
                        }
                    }
                )
            }
        }

        stage('Build') {
            steps {
                parallel (
                    server: {
                        echo 'Building server...'
                        dir('server') {
                            sh 'npm run build'
                        }
                    },
                    client: {
                        echo 'Building client...'
                        dir('crappital-client') {
                            sh 'npm run build-ci'
                        }
                    }
                )
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                dir('server') {
                    sh 'npm run test'
                }
            }
        }

        stage('Build Docker images') {
            steps {
                parallel (
                    server: {
                        echo 'Building server image...'
                        sh 'docker buildx build --load -t crappital-server:${GIT_COMMIT} -f .devcontainer/build/server/Dockerfile.deploy .'
                    },
                    client: {
                        echo 'Building client image...'
                        sh 'docker buildx build --load -t crappital-client:${GIT_COMMIT} -f .devcontainer/build/client/Dockerfile.deploy .'
                    },
                    db: {
                        echo 'Building database image...'
                        sh sh 'docker buildx build --load -t crappital-mongo:${GIT_COMMIT} db/'
                    }
                )
            }
        }

    }
    
}